POST http://localhost:8080/
Content-Type: text/plain

www.ivan.ru

###

# @no-redirect
GET http://localhost:8080/IGsNhCJqYl
Content-Type: text/plain

###

POST http://localhost:8080/api/shorten
Content-Type: application/json

{
  "url": "https://practicum.yandex.ru"
}

###